# Generated by Django 2.2.6 on 2019-10-18 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petalos', '0002_auto_20191018_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flor',
            old_name='valor',
            new_name='precio',
        ),
    ]
