# Generated by Django 2.2.7 on 2019-12-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petalos', '0003_auto_20191018_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('total', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
