# Generated by Django 2.2.7 on 2019-12-08 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petalos', '0004_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='titulo',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='fecha',
        ),
    ]
