# Generated by Django 2.2.7 on 2019-12-08 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petalos', '0005_auto_20191208_0419'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticket',
            new_name='Compra',
        ),
    ]
